name: info_keeper
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: ^0.17.0
  file_picker: ^3.0.4
  grouped_list: ^5.1.2
  flutter_sound: ^9.2.13
  path_provider: ^2.0.11
  scroll_to_index: ^3.0.1
  flutter_animate: ^0.3.0+1
  expansion_widget: ^0.0.3
  permission_handler: ^10.0.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.0.15
  swipe_to: ^1.0.2
  swipe: ^0.0.1
  animated_theme_switcher: ^2.0.6
  syncfusion_flutter_datepicker: ^20.2.40
  location: ^4.4.0
  omni_datetime_picker: ^0.1.2
  open_filex: ^3.4.0
  #firebase for my protection
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  auto_size_text: ^3.0.0
  dismissible_page: ^0.7.3
  modal_bottom_sheet: ^2.1.0
  flutter_parsed_text: ^2.2.1
  url_launcher: ^6.1.5
  # audio_wave: ^0.1.4
  # expandable: ^5.0.1
  # loading_animation_widget: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.17.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
