// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcqZLWyzBM0WCYMK9r2EJm38MYzXYyR7E',
    appId: '1:172665778097:web:148417c5564a754ac85790',
    messagingSenderId: '172665778097',
    projectId: 'info-keeper-10164',
    authDomain: 'info-keeper-10164.firebaseapp.com',
    storageBucket: 'info-keeper-10164.appspot.com',
    measurementId: 'G-G55GWLLSKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0jpUQcYM6X1EwpIyc6q6l7Unp1wiVgEs',
    appId: '1:172665778097:android:3d8207eac4edfe8cc85790',
    messagingSenderId: '172665778097',
    projectId: 'info-keeper-10164',
    storageBucket: 'info-keeper-10164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGgEjF5Z4dEQa_zce2Z1lGzfgDfnaZSKs',
    appId: '1:172665778097:ios:77c6f2ff0fe38ef3c85790',
    messagingSenderId: '172665778097',
    projectId: 'info-keeper-10164',
    storageBucket: 'info-keeper-10164.appspot.com',
    iosClientId: '172665778097-0ufjijiqb4duum5aqspl8io7n0r9o5e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGgEjF5Z4dEQa_zce2Z1lGzfgDfnaZSKs',
    appId: '1:172665778097:ios:77c6f2ff0fe38ef3c85790',
    messagingSenderId: '172665778097',
    projectId: 'info-keeper-10164',
    storageBucket: 'info-keeper-10164.appspot.com',
    iosClientId: '172665778097-0ufjijiqb4duum5aqspl8io7n0r9o5e5.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoKeeper',
  );
}
